import { Job } from '@/types';

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Junior Frontend Developer',
    company: 'Google',
    location: 'Mountain View, CA',
    salary_range: '$120k - $150k',
    experience_level: 'Freshers',
    type: 'Remote',
    description: 'Help us build the next generation of search interfaces.',
    posted_at: '2 hours ago',
    tags: ['React', 'TypeScript', 'Tailwind'],
  },
  {
    id: '2',
    title: 'Senior AI Engineer',
    company: 'OpenAI',
    location: 'San Francisco, CA',
    salary_range: '$200k - $300k',
    experience_level: '7-10 Years',
    type: 'Hybrid',
    description: 'Push the boundaries of what is possible with large language models.',
    posted_at: '5 hours ago',
    tags: ['Python', 'PyTorch', 'Transformers'],
  },
  {
    id: '3',
    title: 'Full Stack Engineer',
    company: 'Stripe',
    location: 'Remote',
    salary_range: '$160k - $220k',
    experience_level: '2-3 Years',
    type: 'Remote',
    description: 'Work on the global infrastructure for internet payments.',
    posted_at: '1 day ago',
    tags: ['Next.js', 'Node.js', 'PostgreSQL'],
  },
  {
    id: '4',
    title: 'Software Engineer II',
    company: 'Microsoft',
    location: 'Redmond, WA',
    salary_range: '$140k - $180k',
    experience_level: '1 Year',
    type: 'On-site',
    description: 'Join the Azure team and build the future of cloud computing.',
    posted_at: '3 hours ago',
    tags: ['C#', '.NET', 'Cloud'],
  },
  {
    id: '5',
    title: 'Lead Product Manager',
    company: 'Amazon',
    location: 'Seattle, WA',
    salary_range: '$180k - $250k',
    experience_level: '4-6 Years',
    type: 'Hybrid',
    description: 'Define the vision for the next generation of AWS services.',
    posted_at: '12 hours ago',
    tags: ['Product', 'Agile', 'Strategy'],
  }
];
